import Head from 'next/head'
import styles from '@/styles/pages/Home.module.scss'
import classNames from "classnames";

export default function Home() {
  return (
    <>
      <Head>
        <title>Handy Tab transfer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classNames(styles.main, 'p-m')}>

      </main>
    </>
  )
}
